# Generated by Django 4.2 on 2024-03-07 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='CanteenProduct',
        ),
    ]
