# Generated by Django 4.2 on 2024-03-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='product_images/blank-profile-pic.jpg', upload_to='product_images/'),
        ),
    ]
