# Generated by Django 4.2 on 2024-02-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='image URL'),
        ),
    ]
