# Generated by Django 4.2 on 2024-03-03 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='somaiya_id',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10', regex='^.{10}$')], verbose_name='somaiya id'),
        ),
    ]
